### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by bytebeats** [chrisbanes/Android-BitmapCache#43]
When the library and the sample are imported into my Eclipse, NoClassDefFoundError occurrd after the sample was runned, the log is below:

02-27 11:15:38.049: E/AndroidRuntime(19734): FATAL EXCEPTION: main
02-27 11:15:38.049: E/AndroidRuntime(19734): java.lang.NoClassDefFoundError: uk.co.senab.bitmapcache.BitmapMemoryLruCache
02-27 11:15:38.049: E/AndroidRuntime(19734):    at uk.co.senab.bitmapcache.BitmapLruCache$Builder.build(BitmapLruCache.java:700)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at uk.co.senab.bitmapcache.samples.SampleApplication.onCreate(SampleApplication.java:52)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:973)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3971)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at android.app.ActivityThread.access$1300(ActivityThread.java:128)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at android.os.Handler.dispatchMessage(Handler.java:99)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at android.os.Looper.loop(Looper.java:137)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at android.app.ActivityThread.main(ActivityThread.java:4517)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at java.lang.reflect.Method.invokeNative(Native Method)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at java.lang.reflect.Method.invoke(Method.java:511)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
02-27 11:15:38.049: E/AndroidRuntime(19734):    at dalvik.system.NativeStart.main(Native Method)

Could you help me check this why?

**Comment by bytebeats** [comment]
Ok, this problem is solved. Just as your Obaining said:"Just remember that you must include all of the required libraries below too.". the libraries of android-support-v4.jar and disklrucache-2.0.1.jar.

Sorry for my troubling you.
