### ISSUE TITLE
Strange gradle issue? java.lang.NoSuchMethodError: No static method getPointerCount(Landroid/view/MotionEvent;)I in class Landroid/support/v4/view/MotionEventCompatEclair

### ISSUE THREAD

**Issue by casolorz** [chrisbanes/Android-BitmapCache#52]
If I add the line below to my gradle config on a library project then the app using that library crashes as soon as I touch the screen. I am not even using the library yet. 

```
compile 'com.github.chrisbanes.bitmapcache:library:2.3+'
```

This is the crash

```
Process: mypacakge, PID: 8762
    java.lang.NoSuchMethodError: No static method getPointerCount(Landroid/view/MotionEvent;)I in class Landroid/support/v4/view/MotionEventCompatEclair; or its super classes (declaration of 'android.support.v4.view.MotionEventCompatEclair' appears in /data/app/mypackage-2/base.apk:classes39.dex)
            at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getPointerCount(MotionEventCompat.java:99)
            at android.support.v4.view.MotionEventCompat.getPointerCount(MotionEventCompat.java:236)
            at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1007)
            at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1137)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1960)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
            at android.view.View.dispatchPointerEvent(View.java:8666)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5868)
            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5920)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:548)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Hand
```

Happens on Android 5.1 on a Nexus 6 and 7 running without proguard. When I try to run proguard I get the following:

```
Error:Execution failed for task ':app:proguardProdRelease'.
> java.io.IOException: Can't write [/workspace/android/app/build/intermediates/classes-proguard/prod/release/classes.jar] (Can't read [/homedir/.gradle/caches/modules-2/files-2.1/com.google.android/support-v4/r7/24d0f6da34c3a2bfcf736ab42d51c91ac821ee22/support-v4-r7.jar(;;;;;;!META-INF/MANIFEST.MF)] (Duplicate zip entry [support-v4-r7.jar:android/support/v4/app/ActivityCompat.class]))
```

In my gradle file for the library I have the following as well well:

```
compile 'com.android.support:support-v4:22+'
compile 'com.jakewharton:disklrucache:2.0.2'
```

**Comment by mntgoat** [comment]
This appears to solve the issue:

```
08596c68	08596c68	Online	LaunchCompatibility{compatible=YES, reason=null}
```

**Comment by casolorz** [comment]
This appears to solve the issue:

```
compile("com.github.chrisbanes.bitmapcache:library:2.3+") {
        exclude module: 'support-v4'
    }
```
