### ISSUE TITLE
'Cannot draw recycled bitmaps' error

### ISSUE THREAD

**Issue by rafali** [chrisbanes/Android-BitmapCache#7]
on my app I sometimes get this exception : 

java.lang.IllegalArgumentException: Cannot draw recycled bitmaps
    at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:789)
    at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
    at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:393)
    at android.widget.ImageView.onDraw(ImageView.java:985)
    at android.view.View.draw(View.java:13712)
    at android.view.View.getDisplayList(View.java:12650)
    at android.view.View.getDisplayList(View.java:12694)
    at android.view.View.draw(View.java:13428)
    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
    at android.view.View.getDisplayList(View.java:12648)
    at android.view.View.getDisplayList(View.java:12694)
    at android.view.View.draw(View.java:13428)
    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
    at android.widget.AbsListView.dispatchDraw(AbsListView.java:2327)
    at android.view.View.draw(View.java:13715)
    at android.widget.AbsListView.draw(AbsListView.java:3653)
    at android.view.View.getDisplayList(View.java:12650)
    at android.view.View.getDisplayList(View.java:12694)
    at android.view.View.draw(View.java:13428)
    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
    at android.view.View.getDisplayList(View.java:12648)
    at android.view.View.getDisplayList(View.java:12694)
    at android.view.View.draw(View.java:13428)
    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
    at android.view.View.getDisplayList(View.java:12648)
    at android.view.View.getDisplayList(View.java:12694)
    at android.view.View.draw(View.java:13428)
    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
    at android.view.View.getDisplayList(View.java:12648)
    at android.view.View.getDisplayList(View.java:12694)
    at android.view.View.draw(View.java:13428)
    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
    at android.view.View.draw(View.java:13715)
    at android.widget.FrameLayout.draw(FrameLayout.java:467)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2211)
    at android.view.View.getDisplayList(View.java:12650)
    at android.view.View.getDisplayList(View.java:12694)
    at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2173)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2045)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1854)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
    at android.view.Choreographer.doFrame(Choreographer.java:532)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5041)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by xiaoym** [comment]
call CacheableBitmapDrawable.setTileModeXY(TileMode.CLAMP, TileMode.CLAMP); before setImageDrawable can solve this problem. After lookup BitmapDrawable.java, you can see setTileModeXY actualy call invalidateSelf, so you can call BitmapDrawable.invalidateSelf (by reflect) also take effect.

**Comment by pboos** [comment]
@rafali Make sure you do something like this:

``` java
Drawable drawable = bitmapCache.put(url, bitmap);
imageView.setImageDrawable(drawable);
```

``` xml
<uk.co.senab.bitmapcache.CacheableImageView
    ... />
```

DO NOT:

``` java
bitmapCache.put(url, bitmap);
imageView.setImageBitmap(bitmap);
```

``` xml
<ImageView
    ... />
```

If you either use ImageView or you set the Bitmap directly, than BitmapCache might think you are not using the bitmap an recycle it.

**Comment by rafali** [comment]
Thanks for the replies!
I was indeed using setImageBitmap instead of setImageDrawable.

**Comment by pboos** [comment]
@chrisbanes Seems like this issue is resolved and can be closed.

Maybe you should add those information from above to the Readme to make it clear. You are saying one "should" use CacheableImageView. But it seems like you **must** use CacheableImageView. And as well that people know they need to use the returned drawable from the put operation instead of the bitmap.

**Comment by chrisbanes** [comment]
@pboos Thanks. I'll do that now.

I also just commit 4672768e983c1847a76e06e4cde0806c29086e99 which improves the code around this.

**Comment by xiaoym** [comment]
@chrisbanes I checkout  4672768  but it seems that getCallback not available on api level 9.

**Comment by chrisbanes** [comment]
@xiaoym: Just use the latest from master.

**Comment by robUx4** [comment]
How about throwing an exception in CacheableImageView.setImageBitmap() to make sure it's not used ?
After all, it will throw an exception elsewhere otherwise...
